export const LIST_USERS = 'LIST_USERS';
export const RETRIEVE_USER = 'RETRIEVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DISABLED_USER = 'DISABLED_USER';
export const TOGGLE_MODAL_DISABLED_USER = 'TOGGLE_MODAL_DISABLED_USER';
